name: Release R package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  
  source:
    name: Package source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: install
          cache: true
          extra-packages: local::., any::pkgdown, any::pkgnet   
      - name: Build package source
        run: R CMD build .
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: MSTWeatherGen_ubuntu-latest
          path: |
            *.tar.gz  

  build:
    name: Build package binaries
    needs: source
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: install
          cache: true
          extra-packages: local::., any::pkgdown, any::pkgnet   
      - uses: actions/download-artifact@v4
      - name: Build package binary
        if: runner.os != 'Linux'
        run: R CMD INSTALL --build *.tar.gz
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: MSTWeatherGen_${{ matrix.os }}
          path: |
            *.tar.gz
            *.zip
            *.tgz

  release:
    name: Create GitHub release
    needs: [source, build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
      - name: Create release and upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            **/*.tar.gz
            **/*.tgz
            **/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}