name: Release R package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  build:
    name: Build source and Windows binary
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Build package
        run: |
          if (Sys.info()[["sysname"]] != "Linux") {
            system("R CMD build .")
          } else {
            system("R CMD INSTALL --build .")
          }
        shell: Rscript {0}

      - uses: actions/upload-artifact@v4
        with:
          name: MSTWeatherGen-${{ matrix.os }}
          path: |
            *.tar.gz
            *.zip
            *.tgz

  release:
    name: Create GitHub release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - name: Create release and upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            MSTWeatherGen-ubuntu-latest/*.tar.gz
            MSTWeatherGen-macos-latest/*.tgz
            MSTWeatherGen-windows-latest/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}